name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget perl build-essential clang make libplist-utils dpkg-dev

      - name: Install Theos (完整环境)
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          export THEOS=$HOME/theos

          # 安装 toolchain（关键）
          bash $THEOS/bin/install-theos

      - name: Build
        run: |
          export THEOS=$HOME/theos
          export PATH=$THEOS/bin:$THEOS/toolchain/linux/iphone/bin:$PATH
          make clean
          make package FINALPACKAGE=1

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: deb
          path: packages/*.deb
